---
# Add an env file with an easier way to pick what stage you want to build up to.
# NOTE change command to actually run something and remove ignore errors.
- hosts: localhost
  tasks:
    - name: Check dependencies
      include: roles/common/tasks/dependencies.yml 
    - name: Bootstrap
      command: echo "bootstrap"
      tags:
        - bootstrap
    - name: Minimal
      command: echo "minimal"
      tags:
        - minimal
    - name: Lite
      command: echo "lite"
      tags:
        - lite
    - name: Desktop
      command: echo "desktop"
      tags:
        - desktop
    - name: Complete
      command: echo "complete"
      tags:
        - complete

  # Become root
  become: true

  # Ignore errors so it goes through the whole playbook
  ignore_errors: yes
