---
# Add an env file with an easier way to pick what stage you want to build up to.
# NOTE change command to actually run something and remove ignore errors.
- hosts: localhost
  tasks:
    - name: Check dependencies
      include: roles/common/tasks/dependencies.yml
    - name: Bootstrap
      include: library/build_bootstrap.yml
      tags:
        - bootstrap
    - name: Minimal
      include: library/build_minimal.yml
      tags:
        - minimal
    - name: Lite
      include: library/build_lite.yml
      tags:
        - lite
    - name: Desktop
      include: library/build_desktop.yml
      tags:
        - desktop
    - name: Complete
      include: library/build_complete.yml
      tags:
        - complete

  # Become root
  become: true

  # Ignore errors so it goes through the whole playbook
  ignore_errors: yes
