---
# Packages that require confirmation
- name: Debconf
  debconf: name='console-setup' question='console-setup/charmap47' value='UTF-8' vtype='select'
  debconf: name='tzdata' question='tzdata/Areas' value='Etc' vtype='select'
  debconf: name='tzdata' question='tzdata/Zones/Etc' value='UTC' vtype='select'
  debconf: name='locales' question='locales/locales_to_be_generated' value='en_GB.UTF-8, UTF-8' vtype='multiselect'
  debconf: name='locales' question='locales/default_environment_locale' value='en_GB.UTF-8' vtype='select'
  debconf: name='keyboard-configuration' question='keyboard-configuration/altgr' value='The default for the keyboard layout' vtype='select'
  debconf: name='keyboard-configuration' question='keyboard-configuration/model' value='Generic 105-key (Intl) PC' vtype='select'
  debconf: name='keyboard-configuration' question='keyboard-configuration/xkb-keymap' value='gb' vtype='select'
  debconf: name='keyboard-configuration' question='keyboard-configuration/compose' value='No compose key' vtype='select'
  debconf: name='keyboard-configuration' question='keyboard-configuration/ctrl_alt_bksp' value='true' vtype='select'
  debconf: name='keyboard-configuration' question='keyboard-configuration/variant' value='English (UK)' vtype='select'

# Install a package nr?
- name: Packages-nr
  action: apt pkg= state=installed
  with_items:
  - cifs-utils

# Install some packages
- name: Packages
  action: apt pkg= state=installed
  with_items:
    - ssh
    - locales
    - less
    - fbset
    - sudo
    - psmisc
    - strace
    - module-init-tools
    - ed
    - ncdu
    - crda
    - console-setup
    - keyboard-configuration
    - debconf-utils
    - parted
    - unzip
    - build-essential
    - manpages-dev
    - python
    - bash-completion
    - gdb
    - pkg-config
    - python-rpi.gpio
    - v4l-utils
    - avahi-daemon
    - lua5.1
    - luajit
    - hardlink
    - ca-certificates
    - curl
    - fake-hwclock
    - ntp
    - nfs-common
    - usbutils
    - libraspberrypi-dev
    - libraspberrypi-doc
    - libfreetype6-dev
    - dosfstools
    - dphys-swapfile
    - raspberrypi-sys-mods
    - pi-bluetooth
    - apt-listchanges
    - usb-modeswitch
    - apt-transport-https

- name: Extra
  file: src=files/regenerate_ssh_host_keys.service dest=${ROOTFS_DIR}/lib/systemd/system/ mode=0644
  file: src=files/apply_noobs_os_config dest=${ROOTFS_DIR}/etc/init.d/ mode=0755
  file: src=files/resize2fs_once dest=${ROOTFS_DIR}/etc/init.d/ mode=0755
  file: dest=${ROOTFS_DIR}/etc/systemd/system/rc-local.service.d state=directory
  file: src=files/ttyoutput.conf dest=${ROOTFS_DIR}/etc/systemd/system/rc-local.service.d/ mode=0644
  file: src=files/50raspi dest=${ROOTFS_DIR}/etc/apt/apt.conf.d/ mode=0644

# Systemctl
- name: Services
  command: systemctl disable hwclock.sh
  command: systemctl disable nfs-common
  command: systemctl disable rpcbind
  command: systemctl disable ssh
  command: systemctl enable regenerate_ssh_host_keys
  command: systemctl enable apply_noobs_os_config
  command: systemctl enable resize2fs_once

# Set up Groups
- group:
    name: input state: present system: yes
    name: spi state: present system: yes
    name: ic2 state: present system: yes
    name: gpio state: present system: yes

# Add pi user to the groups
- user:
    name: pi
    groups: adm,dialout,cdrom,audio,users,sudo,video,games,plugdev,input,gpio,spi,i2c,netdev

# Last bit of set up
- name: Services
  command: setupcon --force --save-only -v
  command: usermod --pass='*' root

# Remove ssh key
- name: Extra
  file: path: ${ROOTFS_DIR}/etc/ssh/ssh_host_*_key* state=absent
