---
# Configure packages before installing
- name: STAGE 3 - install-packages/debconf
  debconf:
    name: "{{ item.name }}"
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  with_items:
    - { name: 'rpi-chromium-mods', question: 'rpi-chromium-mods/adobe', value: 'true', vtype: 'note' }

# Install apt packages with --no-install-recommends
- name: STAGE 3 - install-packages/packages-nr
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: no
  with_items:
  - xserver-xorg-video-fbdev
  - xserver-xorg
  - xinit
  - xserver-xorg-video-fbturbo
  - epiphany-browser
  - lxde
  - lxtask
  - menu-xdg
  - gksu
  - netsurf-gtk
  - zenity
  - xdg-utils
  - gvfs-backends
  - gvfs-fuse
  - lightdm
  - gnome-themes-standard-data
  - gnome-icon-theme

# Install apt packages
- name: STAGE 3 - install-packages/packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
  - gstreamer1.0-x
  - gstreamer1.0-omx
  - gstreamer1.0-plugins-base
  - gstreamer1.0-plugins-good
  - gstreamer1.0-plugins-bad
  - gstreamer1.0-alsa
  - gstreamer1.0-libav
  - xpdf
  - gtk2-engines
  - alsa-utils
  - desktop-base
  - git-core rpi-update
  - omxplayer
  - raspberrypi-artwork
  - policykit-1
  - gvfs
  - rfkill
  - chromium-browser
  - rpi-chromium-mods

# Setup update-alternatives for the browser
- name: STAGE 3 - install-packages/update-alternatives
  alternatives:
    name: "{{item.name}}"
    link: "{{item.link}}"
    path: "{{item.path}}"
    priority: "{{item.priority}}"
  with_items:
  - {name: '\ x-www-browser', link: '/usr/bin/x-www-browser', path: '/usr/bin/chromium-browser', priority: '86'}
  - {name: '\ gnome-www-browser', link: '/usr/bin/gnome-www-browser', path: '/usr/bin/chromium-browser', priority: '86'}