---
# SORT OUT PYTHON GAMES MESS
# Set up python games
#- name: Python Games
#  shell: HASH=`wget https://api.github.com/repos/KenT2/python-games/git/refs/heads/master -qO -| grep \"sha\" | cut -f 2 -d ':' | cut -f 2 -d \"`
#  shell: if [ -f files/python_games.hash ]; then HASH_LOCAL=`cat files/python_games.hash` fi
#  shell: if [ ! -e files/python_games.tar.gz ] || [ "$HASH" != "$HASH_LOCAL"  ]; then wget "https://github.com/KenT2/python-games/tarball/master" -O files/python_games.tar.gz echo $HASH > files/python_games.hash fi
#
#- name: Python Games folders
#  file: path=/${ROOTFS_DIR}/home/pi/python_games state=directory owner=1000 group=1000
#  unarchive: src=files/python_games.tar.gz dest=${ROOTFS_DIR}/home/pi/python_games
#  file: path=${ROOTFS_DIR}/home/pi/python_games state=directory recurse=yes owner=1000 group=1000
#  file: path=${ROOTFS_DIR}/home/pi/python_games/launcher.sh mode=+x


# Set up pip3
- name: STAGE 4 - extras/pip
  file:
    scr: pip3
    dest: /usr/bin/pip-3.2
    state: link
    force: true

# Create directories as owner=1000 and group=1000
- name: STAGE 4 - extras/create_directories
  file:
    path: "{{item}}"
    owner: 1000
    group: 1000
    state: directory
  with_items:
    - /home/pi/.local
    - /home/pi/.local/share
    - /home/pi/.local/share/applications
    - /home/pi/.local/share/desktop-directories
    - /home/pi/Documents state=directory
    - /home/pi/Documents/BlueJ\ Projects
    - /home/pi/Documents/Greenfoot\ Projects
    - /home/pi/Documents/Scratch\ Projects

- name: STAGE 4 - extras/rsync
  synchronize:
    archive: yes
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    owner: 1000
    group: 1000
  with_item:
    - {src: '/usr/share/doc/BlueJ/', dest: '/home/pi/Documents/BlueJ Projects'}
    - {src: '/usr/share/doc/Greenfoot/', dest: '/home/pi/Documents/Greenfoot Projects'}
    - {src: '/usr/share/scratch/Projects/Demos/', dest: '/home/pi/Documents/Scratch Projects'}