---
- name: Install dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - quilt
    - parted
    - realpath
    - qemu-user-static
    - debootstrap
    - zerofree
    - pxz
    - zip
    - dosfstools
    - bsdtar
    - libcap2-bin
    - grep
    - rsync
