---
# Configure packages before installing
- name: STAGE 4 - install-packages/debconf
  debconf:
    name: "{{ item.name }}"
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  with_items:
    - { name: 'jackd2', question: 'jackd/tweak_rt_limits', value: 'true', vtype: 'boolean' }
    - { name: 'wolfram-engine', question: 'shared/accepted-wolfram-eula', value: 'true', vtype: 'boolean' }

# Install apt packages with --no-install-recommends
- name: STAGE 4 - install-packages/packages-nr
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: no
  with_items:
    - libreoffice
    - libreoffice-gtk
    - timidity
    - pi-package

# Install apt packages
- name: STAGE 4 - install-packages/packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
  - java-common
  - oracle-java8-jdk
  - libreoffice-sdbc-hsqldb
  - sonic-pi
  - python
  - idle
  - python3-pygame
  - python-pygame
  - python-tk
  - python3
  - idle3
  - python3-tk
  - python3-pgzero
  - python-serial
  - python3-serial
  - python-picamera
  - python3-picamera
  - debian-reference-en
  - dillo
  - x2x
  - wolfram-engine
  - raspberrypi-net-mods
  - raspberrypi-ui-mods
  - smartsim
  - penguinspuzzle
  - python-pip
  - python3-pip
  - python3-numpy
  - pypy
  - python3-pifacecommon
  - python3-pifacedigitalio
  - python3-pifacedigital-scratch-handler
  - python-pifacecommon
  - python-pifacedigitalio
  - minecraft-pi
  - python-minecraftpi
  - alacarte
  - rc-gui
  - sense-hat
  - claws-mail
  - tree
  - scratch
  - nuscratch
  - greenfoot
  - bluej
  - nodered
  - libgl1-mesa-dri
  - libgles1-mesa
  - libgles2-mesa
  - xcompmgr
  - geany
  - piclone
  - pulseaudio-module-bluetooth
  - wiringpi
  - pigpio
  - python-pigpio
  - python3-pigpio
  - raspi-gpio
  - python-gpiozero
  - python3-gpiozero
  - python3-rpi.gpio
  - python-spidev
  - python3-spidev
  - realvnc-vnc-server
  - realvnc-vnc-viewer
  - python-twython
  - python3-twython
  - python-smbus
  - python3-smbus
  - python-flask
  - python3-flask
  - python-picraft
  - python3-picraft
  - python3-codebug-tether
  - python3-codebug-i2c-tether
  - python-sense-emu
  - python3-sense-emu
  - sense-emu-tools
  - python-sense-emu-doc
  - pprompt

# Remove root VNC private key
- name: STAGE 4 - install-packages/extras
  file:
    path: /root/.vnc/private.key
    state: absent